### ISSUE TITLE
Stalls out server if hooked up to AE2 system with autocrafting

### ISSUE THREAD

**Issue by Time6628** [LatvianModder/Project-EX#23]
Stall report is below. 
```
Stall report from 2019-03-21 15:36:31 -0400, 105 threads, stalled for at least 30000 ms.
Heap memory usage: 2966 / 12582 MB (max. 12582 MB).
Created by sampler 1.80 (MC 1.12).

"Server thread" #20 prio=5
RUNNABLE
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:737)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:668)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:650)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at com.latmod.mods.projectex.tile.TileLink.extractItem(TileLink.java:314)
	at appeng.parts.misc.ItemHandlerAdapter.extractItems(ItemHandlerAdapter.java:134)
	at appeng.parts.misc.ItemHandlerAdapter.extractItems(ItemHandlerAdapter.java:53)
	at appeng.me.storage.MEPassThrough.extractItems(MEPassThrough.java:63)
	at appeng.me.storage.MEInventoryHandler.extractItems(MEInventoryHandler.java:117)
	at appeng.me.storage.NetworkInventoryHandler.extractItems(NetworkInventoryHandler.java:228)
	at appeng.me.cache.NetworkMonitor.extractItems(NetworkMonitor.java:93)
	at appeng.crafting.MECraftingInventory.<init>(MECraftingInventory.java:141)
	at appeng.crafting.CraftingJob.<init>(CraftingJob.java:90)
	at appeng.me.cache.CraftingGridCache.beginCraftingJob(CraftingGridCache.java:499)
	at appeng.core.sync.packets.PacketCraftRequest.serverPacketData(PacketCraftRequest.java:100)
	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:57)
	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:126)
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193)
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
	- locked java.util.ArrayDeque@4b71e808
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by LatvianModder** [comment]
Added option to change max output for Links
