### ISSUE TITLE
ProjectEX-1.1.0.33 not compatible with ProjectE-1.12.2-PE1.4.1

### ISSUE THREAD

**Issue by CopperBoltwire** [LatvianModder/Project-EX#36]
Suggestion:
When ever you release an update to your mod, please write in the changelog which version of ProjectE it was made for? Cause it apparently seems to be specific which version of PE your versions are written for.

Had to install PE1.4.0 to make it work fine, but i can't update PE to the new 1.4.1 because your mod is version dependent apparently... 

Just sayin...

**Comment by ToMe25** [comment]
I had a Crash with ProjectE too.
The main Part of the Crashlog was:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProjectE (projecte)
Caused by: java.lang.AbstractMethodError: Method com/latmod/mods/projectex/item/ItemColossalStar.getStoredEmc(Lnet/minecraft/item/ItemStack;)J is abstract
    at com.latmod.mods.projectex.item.ItemColossalStar.getStoredEmc(ItemColossalStar.java)
    at moze_intel.projecte.utils.EMCHelper.getStoredEMCBonus(EMCHelper.java:327)
    at moze_intel.projecte.utils.EMCHelper.getEmcValue(EMCHelper.java:250)
    at moze_intel.projecte.playerData.Transmutation.cacheFullKnowledge(Transmutation.java:38)
    at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:149)
    at moze_intel.projecte.PECore.serverStarting(PECore.java:175)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:217)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by boosterdev** [comment]
apparently this only happends on world load or world creation

**Comment by LatvianModder** [comment]
fixed
