### ISSUE TITLE
Game crashed!

### ISSUE THREAD

**Issue by qwerty-a11y** [LatvianModder/Project-EX#82]
After I install the Project EX, the game interface loads to collapse.
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-06-06 21:36:20 CST
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Project EX (projectex)
Caused by: java.lang.NoClassDefFoundError: moze_intel/projecte/api/event/PlayerAttemptLearnEvent
    at com.latmod.mods.projectex.tile.AlchemyTableRecipes.add(AlchemyTableRecipes.java:26)
    at com.latmod.mods.projectex.tile.AlchemyTableRecipes.addSteps(AlchemyTableRecipes.java:35)
    at com.latmod.mods.projectex.tile.AlchemyTableRecipes.addDefaultRecipes(AlchemyTableRecipes.java:41)
    at com.latmod.mods.projectex.ProjectEX.onInit(ProjectEX.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: moze_intel.projecte.api.event.PlayerAttemptLearnEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (x86) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
  Memory: 209731944 bytes (200 MB) / 805306368 bytes (768 MB) up to 838860800 bytes (800 MB)
  JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xss1M -Xmx800m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 38 mods loaded, 37 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version                      | Source                                            | Signature                                |
       |:----- |:------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft           | 1.12.2                       | minecraft.jar                                     | None                                     |
       | LCHI  | mcp                 | 9.42                         | minecraft.jar                                     | None                                     |
       | LCHI  | FML                 | 8.0.99.99                    | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge               | 14.23.5.2854                 | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | lolipickaxe         | 1.2.16f                      | [氪金萝莉]LoliPickaxe-1.2.16f-1.12.2.jar              | None                                     |
       | LCHI  | manaita_plus        | 1.0.0                        | [砧板]Manaita+Plus-1.12.2-1.0.0.jar                 | None                                     |
       | LCHI  | codechickenlib      | 3.2.3.358                    | codechickenlib[1.12.2].jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | redstoneflux        | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHI  | brandonscore        | 2.4.18                       | BrandonsCore-1.12.2-2.4.18.210-universal.jar      | None                                     |
       | LCHI  | hammercore          | 2.0.6.13                     | HammerCore-1.12.2-2.0.6.13.jar                    | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHI  | jei                 | 4.15.0.268                   | JEI物品管理器[1.12.2].jar                              | None                                     |
       | LCHI  | projecte            | 1.12-PE1.0.0                 | 等价交换[1.12.2].jar                                  | None                                     |
       | LCHI  | expequiv            | 13r                          | ExpandedEquivalence-1.12.2-13r.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHI  | lootoverhaul        | 1.2                          | LootOverhaul-1.2.jar                              | None                                     |
       | LCHI  | mcty                | 1.0.1                        | MC牌汤圆[1.12.2].jar                                 | None                                     |
       | LCHI  | neat                | 1.4-17                       | Neat+1.4-17.jar                                   | None                                     |
       | LCHE  | projectex           | 1.2.0.39                     | ProjectEX-1.2.0.39.jar                            | None                                     |
       | LCH   | projectintelligence | 1.0.9                        | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar | None                                     |
       | LCH   | scp                 | 2.1.1                        | SCP基金会[1.12.2].jar                                | None                                     |
       | LCH   | vanillafix          | 1.0.10-SNAPSHOT              | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCH   | worldedit           | 6.1.8                        | 创世神[1.12.2].jar                                   | None                                     |
       | LCH   | worldeditcuife2     | 2.1.2-mf-1.12.2-14.23.0.2487 | 创世神选区显示[1.12.2].jar                               | None                                     |
       | LCH   | persistentbits      | 1.0.6a                       | 区块加载器[1.12.2].jar                                 | None                                     |
       | LCH   | metamorph           | 1.1.4                        | 变形[1.12.2].jar                                    | None                                     |
       | LCH   | lucky               | 7.5.0                        | 幸运方块[1.12.x].jar                                  | None                                     |
       | LCH   | mobbattle           | 2.3.3                        | 怪物大乱斗[1.12.2].jar                                 | None                                     |
       | LCH   | avaritia            | 3.2.0                        | 无尽贪婪[1.12.2].jar                                  | None                                     |
       | LCH   | infinity            | 0.13.2                       | 无限物品编辑器[1.12.2].jar                               | None                                     |
       | LCH   | twilightforest      | 3.7.424                      | 暮色森林[1.12.2].jar                                  | None                                     |
       | LCH   | uncrafted           | 3.0.1                        | 更多合成配方[1.12.2].jar                                | None                                     |
       | LCH   | autopickup          | 2.5.1                        | 自动拾取[1.12.2].jar                                  | None                                     |
       | LCH   | customnpcs          | 1.12                         | 自定义·NPC[1.12.2].jar                               | None                                     |
       | LCH   | veinminer           | 0.38.2                       | 连锁挖矿[1.12.2].jar                                  | None                                     |
       | LCH   | veinminermodsupport | 0.38.2                       | 连锁挖矿[1.12.2].jar                                  | None                                     |
       | LCH   | randomthings        | 4.2.7.3                      | 随意制作[1.12.2].jar                                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | appleskin           | 1.0.9                        | 饥饿值显示[1.12.2].jar                                 | None                                     |
       | LCH   | pistonexpansion     | 1.0.1                        | 自定义活塞[1.12.2].jar                                 | 7b14aaee2dd17b12a140baecab28948fff3a263f |
       | UD    | lolipickaxecore     | 1.2.16f                      | minecraft.jar                                     | None                                     |
  Loaded coremods (and transformers): PistonExpansionLoadingPlugin (pistonexpansion-1.12.2-1.0.1-core.jar)
                                        com.github.upcraftlp.pistonexpansion.asm.PistonExpansionTransformer
                                      LoliPickaxeCore ([氪金萝莉]LoliPickaxe-1.2.16f-1.12.2.jar)
                                        com.anotherstar.core.transformer.LoliPickaxeTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.6.13.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      LoadingPlugin (随意制作[1.12.2].jar)
                                        lumien.randomthings.asm.ClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 7300 Series'
  HammerCore Debug Information: Dependent Mods:
                                    -Expanded Equivalence (expequiv) @13r
  Suspected Mods: Project EX (projectex)

**Comment by Snapshotlight** [comment]
Expanded Equivanlance似乎不和这个模组兼容，而且作者毕竟几个月没更新了，现在估计多半是弃坑了
